### ISSUE TITLE
Doesn't return element with no dependency

### ISSUE THREAD

**Issue by musitdev** [gifnksm/topological-sort-rs#15]
If I add those elements:
1 no dependency
2 no dependency
3 depends on 2
pop_all only return 2 then 3. 
1 is never return.

**Comment by ProgVal** [comment]
Hi,

I can't reproduce the issue. This test always succeeds:

```
    #[test]
    fn test_issue15() {
        let mut ts = TopologicalSort::new();
        assert!(ts.insert(1));
        assert!(ts.insert(2));
        ts.add_dependency(2, 3);

        let elem_1 = ts.pop();
        if let Some(1) = elem_1 {
            assert_eq!(Some(2), ts.pop());
            assert_eq!(Some(3), ts.pop());
            assert_eq!(None, ts.pop());
        }
        else {
            assert_eq!(Some(2), elem_1);
            assert_eq!(Some(3), ts.pop());
            assert_eq!(Some(1), ts.pop());
            assert_eq!(None, ts.pop());
        }
    }
```

**Comment by musitdev** [comment]
Hello,
It's a long time. I've forgotten that I've open this issue. Don't know why I didn't put code. I'll try to recreate it and put the code.

**Comment by musitdev** [comment]
I redo the test and it works. I didn't find the test I've done at that time. A lot off thing change since and all my test has changed. 
I've surely done a mistake.
